In [1]:
import random
import datetime
import numpy as np
import copy
from datetime import datetime, timedelta
import pymysql


In [25]:
#a=datetime.today() - timedelta(i)#+사전 컨테이너 레이블링
#b=a.strftime('%d') 
# #dictionary = dict(zip(l,r))
# #print(dictionary)

In [26]:
#!pip install PyMySQL

In [2]:
def rest1(array,date):
    p=array
    if all(p[0,0,0:]==-100)==True:
        p[0][0][0]=date
    elif p[0][0][1]==-100:
        if p[0][0][0]<=date:
            p[0][0][1]=p[0][0][0]
            p[0][0][0]=date

        elif p[0][0][0]>date:
            p[0][0][1]=date

    elif p[0][0][2]==-100:

        if p[0][0][1]>=date:
            p[0][0][2]=date 

        elif p[0][0][1]<date and p[0][0][0]>date:
            p[0][0][2]=p[0][0][1]
            p[0][0][1]=date
        elif p[0][0][0]<=date:
            p[0][0][2]=p[0][0][1]
            p[0][0][1]=p[0][0][0]
            p[0][0][0]=date

    else:
        rest2(p,date)
    return array

def rest2(array,date):
    p=array  
    if all(p[0,1,0:]==-100)==True:
        p[0][1][0]=date
    elif p[0][1][1]==-100:
        if p[0][1][0]<=date:
            p[0][1][1]=p[0][1][0]
            p[0][1][0]=date

        elif p[0][1][0]>date:
            p[0][1][1]=date

    elif p[0][1][2]==-100:

        if p[0][1][1]>=date:
            p[0][1][2]=date 

        elif p[0][1][1]<date and p[0][1][0]>date:
            p[0][1][2]=p[0][1][1]
            p[0][1][1]=date
        elif p[0][1][0]<=date:
            p[0][1][2]=p[0][1][1]
            p[0][1][1]=p[0][1][0]
            p[0][1][0]=date
    else:
        print('2구역 다참')
        rest3(p,date)
    return array

def rest3(array,date):
    p=array
    if all(p[1,0,0:]==-100)==True:
        p[1][0][0]=date
    elif p[1][0][1]==-100:
        if p[1][0][0]<=date:
            p[1][0][1]=p[1][0][0]
            p[1][0][0]=date

        elif p[1][0][0]>date:
            p[1][0][1]=date

    elif p[1][0][2]==-100:

        if p[1][0][1]>=date:
            p[1][0][2]=date 

        elif p[1][0][1]<date and p[1][0][0]>date:
            p[1][0][2]=p[1][0][1]
            p[1][0][1]=date
        elif p[1][0][0]<=date:
            p[1][0][2]=p[1][0][1]
            p[1][0][1]=p[1][0][0]
            p[1][0][0]=date

    else:
        print('3구역 다참')
        rest4(p,date)
    return array

def rest4(array,date):
    p=array
    if all(p[1,1,0:]==-100)==True:
        p[1][1][0]=date
    elif p[1][1][1]==-100:
        if p[1][1][0]<=date:
            p[1][1][1]=p[1][1][0]
            p[1][1][0]=date

        elif p[1][1][0]>date:
            p[1][1][1]=date

    elif p[1][1][2]==-100:

        if p[1][1][1]>=date:
            p[1][1][2]=date 

        elif p[1][1][1]<date and p[1][1][0]>date:
            p[1][1][2]=p[1][1][1]
            p[1][1][1]=date
        elif p[1][1][0]<=date:
            p[1][1][2]=p[1][1][1]
            p[1][1][1]=p[1][1][0]
            p[1][1][0]=date

    else:
        print('4구역 다참')
        rest5(p,date)
            
    return array

def rest5(array,date):
    p=array
    if all(p[2,0,0:]==-100)==True:
        p[2][0][0]=date
    elif p[2][0][1]==-100:
        if p[2][0][0]<=date:
            p[2][0][1]=p[2][0][0]
            p[2][0][0]=date

        elif p[2][0][0]>date:
            p[2][0][1]=date

    elif p[2][0][2]==-100:

        if p[2][0][1]>=date:
            p[2][0][2]=date 

        elif p[2][0][1]<date and p[2][0][0]>date:
            p[2][0][2]=p[2][0][1]
            p[2][0][1]=date
        elif p[2][0][0]<=date:
            p[2][0][2]=p[2][0][1]
            p[2][0][1]=p[2][0][0]
            p[2][0][0]=date

    else:
        print('5구역 다참')
        rest6(p,date)
            
    return array

def rest6(array,date):
    p=array     
    if all(p[2,1,0:]==-100)==True:
        p[2][1][0]=date
    elif p[2][1][1]==-100:
        if p[2][1][0]<=date:
            p[2][1][1]=p[2][1][0]
            p[2][1][0]=date

        elif p[2][1][0]>date:
            p[2][1][1]=date

    elif p[2][1][2]==-100:

        if p[2][1][1]>=date:
            p[2][1][2]=date 

        elif p[2][1][1]<date and p[2][1][0]>date:
            p[2][1][2]=p[2][1][1]
            p[2][1][1]=date
        elif p[2][1][0]<=date:
            p[2][1][2]=p[2][1][1]
            p[2][1][1]=p[2][1][0]
            p[2][1][0]=date

    else:
        print('6구역 다참')
        rest7(array,date)
    return array

def rest7(array,date):
    p=array 
    if all(p[3,0,0:]==-100)==True:
        p[3][0][0]=date
    elif p[3][0][1]==-100:
        if p[3][0][0]<=date:
            p[3][0][1]=p[3][0][0]
            p[3][0][0]=date

        elif p[3][0][0]>date:
            p[3][0][1]=date

    elif p[3][0][2]==-100:

        if p[3][0][1]>=date:
            p[3][0][2]=date 

        elif p[3][0][1]<date and p[3][0][0]>date:
            p[3][0][2]=p[3][0][1]
            p[3][0][1]=date
        elif p[3][0][0]<=date:
            p[3][0][2]=p[3][0][1]
            p[3][0][1]=p[3][0][0]
            p[3][0][0]=date

    else:
        print('7구역 다참')
        rest8(p,date)
    return array

def rest8(array,date):
    p=array 
    if all(p[3,1,0:]==-100)==True:
        p[3][1][0]=date
    elif p[3][1][1]==-100:
        if p[3][1][0]<=date:
            p[3][1][1]=p[3][1][0]
            p[3][1][0]=date

        elif p[3][1][0]>date:
            p[3][1][1]=date

    elif p[3][1][2]==-100:

        if p[3][1][1]>=date:
            p[3][1][2]=date 

        elif p[3][1][1]<date and p[3][1][0]>date:
            p[3][1][2]=p[3][1][1]
            p[3][1][1]=date
        elif p[3][1][0]<=date:
            p[3][1][2]=p[3][1][1]
            p[3][1][1]=p[3][1][0]
            p[3][1][0]=date

    else:
        print('8구역 다참')
        rest1(array,date)
    return array  

In [3]:
def new(array,date):
    p=array
    b=(date%8)+1
    if b==1:
        if all(p[0,0,0:]==-100)==True:
            p[0][0][0]=date
        elif p[0][0][1]==-100:
            if p[0][0][0]<=date:
                p[0][0][1]=p[0][0][0]
                p[0][0][0]=date
            
            elif p[0][0][0]>date:
                p[0][0][1]=date

        elif p[0][0][2]==-100:
           
            if p[0][0][1]>=date:
                p[0][0][2]=date 
            
            elif p[0][0][1]<date and p[0][0][0]>date:
                p[0][0][2]=p[0][0][1]
                p[0][0][1]=date
            elif p[0][0][0]<=date:
                p[0][0][2]=p[0][0][1]
                p[0][0][1]=p[0][0][0]
                p[0][0][0]=date
                
        else:
            print('1구역 다참')
            rest2(p,date)
            

    elif b==2:
        if all(p[0,1,0:]==-100)==True:
            p[0][1][0]=date
        elif p[0][1][1]==-100:
            if p[0][1][0]<=date:
                p[0][1][1]=p[0][1][0]
                p[0][1][0]=date
            
            elif p[0][1][0]>date:
                p[0][1][1]=date

        elif p[0][1][2]==-100:
           
            if p[0][1][1]>=date:
                p[0][1][2]=date 
            
            elif p[0][1][1]<date and p[0][1][0]>date:
                p[0][1][2]=p[0][1][1]
                p[0][1][1]=date
            elif p[0][1][0]<=date:
                p[0][1][2]=p[0][1][1]
                p[0][1][1]=p[0][1][0]
                p[0][1][0]=date
        else:
            print('2구역 다참')
            rest3(p,date)
            
       
        #(1,0-1,y)       
    elif b==3:
        if all(p[1,0,0:]==-100)==True:
            p[1][0][0]=date
        elif p[1][0][1]==-100:
            if p[1][0][0]<=date:
                p[1][0][1]=p[1][0][0]
                p[1][0][0]=date
            
            elif p[1][0][0]>date:
                p[1][0][1]=date

        elif p[1][0][2]==-100:
           
            if p[1][0][1]>=date:
                p[1][0][2]=date 
        
            elif p[1][0][1]<date and p[1][0][0]>date:
                p[1][0][2]=p[1][0][1]
                p[1][0][1]=date
            elif p[1][0][0]<=date:
                p[1][0][2]=p[1][0][1]
                p[1][0][1]=p[1][0][0]
                p[1][0][0]=date
                
        else:
            print('3구역 다참')
            rest4(p,date)
            


    elif b==4:
        if all(p[1,1,0:]==-100)==True:
            p[1][1][0]=date
        elif p[1][1][1]==-100:
            if p[1][1][0]<=date:
                p[1][1][1]=p[1][1][0]
                p[1][1][0]=date
            
            elif p[1][1][0]>date:
                p[1][1][1]=date

        elif p[1][1][2]==-100:
           
            if p[1][1][1]>=date:
                p[1][1][2]=date 
            
            elif p[1][1][1]<date and p[1][1][0]>date:
                p[1][1][2]=p[1][1][1]
                p[1][1][1]=date
            elif p[1][1][0]<=date:
                p[1][1][2]=p[1][1][1]
                p[1][1][1]=p[1][1][0]
                p[1][1][0]=date
                
        else:
            print('4구역 다참')
            rest5(p,date)
            
    #(2,0-1,y) 
    elif b==5:
        if all(p[2,0,0:]==-100)==True:
            p[2][0][0]=date
        elif p[2][0][1]==-100:
            if p[2][0][0]<=date:
                p[2][0][1]=p[2][0][0]
                p[2][0][0]=date
            
            elif p[2][0][0]>date:
                p[2][0][1]=date

        elif p[2][0][2]==-100:
           
            if p[2][0][1]>=date:
                p[2][0][2]=date 
            
            elif p[2][0][1]<date and p[2][0][0]>date:
                p[2][0][2]=p[2][0][1]
                p[2][0][1]=date
            elif p[2][0][0]<=date:
                p[2][0][2]=p[2][0][1]
                p[2][0][1]=p[2][0][0]
                p[2][0][0]=date
                
        else:
            print('5구역 다참')
            rest6(p,date)
            

        
        
    elif b==6:         
        if all(p[2,1,0:]==-100)==True:
            p[2][1][0]=date
        elif p[2][1][1]==-100:
            if p[2][1][0]<=date:
                p[2][1][1]=p[2][1][0]
                p[2][1][0]=date
            
            elif p[2][1][0]>date:
                p[2][1][1]=date

        elif p[2][1][2]==-100:
           
            if p[2][1][1]>=date:
                p[2][1][2]=date 
            
            elif p[2][1][1]<date and p[2][1][0]>date:
                p[2][1][2]=p[2][1][1]
                p[2][1][1]=date
            elif p[2][1][0]<=date:
                p[2][1][2]=p[2][1][1]
                p[2][1][1]=p[2][1][0]
                p[2][1][0]=date
                
        else:
            print('6구역 다참')
            rest7(p,date)
           
        #(3,0-1,y) 
    elif b==7:
        if all(p[3,0,0:]==-100)==True:
            p[3][0][0]=date
        elif p[3][0][1]==-100:
            if p[3][0][0]<=date:
                p[3][0][1]=p[3][0][0]
                p[3][0][0]=date
            
            elif p[3][0][0]>date:
                p[3][0][1]=date

        elif p[3][0][2]==-100:
           
            if p[3][0][1]>=date:
                p[3][0][2]=date 
            
            elif p[3][0][1]<date and p[3][0][0]>date:
                p[3][0][2]=p[3][0][1]
                p[3][0][1]=date
            elif p[3][0][0]<=date:
                p[3][0][2]=p[3][0][1]
                p[3][0][1]=p[3][0][0]
                p[3][0][0]=date
                
        else:
            print('7구역 다참')
            rest8(p,date)
            

    elif b==8:
        if all(p[3,1,0:]==-100)==True:
            p[3][1][0]=date
        elif p[3][1][1]==-100:
            if p[3][1][0]<=date:
                p[3][1][1]=p[3][1][0]
                p[3][1][0]=date
            
            elif p[3][1][0]>date:
                p[3][1][1]=date

        elif p[3][1][2]==-100:
           
            if p[3][1][1]>=date:
                p[3][1][2]=date 
            
            elif p[3][1][1]<date and p[3][1][0]>date:
                p[3][1][2]=p[3][1][1]
                p[3][1][1]=date
            elif p[3][1][0]<=date:
                p[3][1][2]=p[3][1][1]
                p[3][1][1]=p[3][1][0]
                p[3][1][0]=date
                
        else:
            print('8구역 다참')
            rest1(p,date)
           
            
        
    return array

In [4]:
l=[] #원래 컨테이너 빼는 날짜
for i in range(10):#length(컨테이너개수)
    l.append(i+1)
    
for i in range(14):#24-length
    l.append(-100)
    
l.sort()
print(l)

[-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [5]:
p=np.zeros([4,2,3])-100

for i in range(24):
    if l[i]==-100:
        continue 
    #(0,0-1,y)
    elif (l[i]%8)+1==1:
        if all(p[0,0,0:]==-100)==True:
            p[0][0][0]=l[i]
        elif p[0][0][1]==-100 and p[0][0][0]<=l[i]:
            p[0][0][1]=p[0][0][0]
            p[0][0][0]=l[i]

        elif p[0][0][2]==-100 and p[0][0][1]<=l[i]:
            p[0][0][2]=p[0][0][1]
            p[0][0][1]=p[0][0][0]
            p[0][0][0]=l[i]
        else:
            print('1구역 다참')

    elif (l[i]%8)+1==2:
        if all(p[0,1,0:]==-100)==True:
            p[0][1][0]=l[i]
        elif p[0][1][1]==-100 and p[0][1][0]<=l[i]:
            p[0][1][1]=p[0][1][0]
            p[0][1][0]=l[i]
        elif p[0][1][2]==-100 and p[0][1][1]<=l[i]:
            p[0][1][2]=p[0][1][1]
            p[0][1][1]=p[0][1][0]
            p[0][1][0]=l[i]
        else:
            print('2구역 다참')
    #(1,0-1,y)       
    elif (l[i]%8)+1==3:
        if all(p[1,0,0:]==-100)==True:
            p[1][0][0]=l[i]
        elif p[1][0][1]==-100 and p[1][0][0]<=l[i]:
            p[1][0][1]=p[1][0][0]
            p[1][0][0]=l[i]
        elif p[1][0][2]==-100 and p[1][0][1]<=l[i]:
            p[1][0][2]=p[1][0][1]
            p[1][0][1]=p[1][0][0]
            p[1][0][0]=l[i]
        else:
            print('3구역 다참')

    elif (l[i]%8)+1==4:
        if all(p[1,1,0:]==-100)==True:
            p[1][1][0]=l[i]
        elif p[1][1][1]==-100 and p[1][1][0]<=l[i]:
            p[1][1][1]=p[1][1][0]
            p[1][1][0]=l[i]
        elif p[1][1][2]==-100 and p[1][1][1]<=l[i]:
            p[1][1][2]=p[1][1][1]
            p[1][1][1]=p[1][1][0]
            p[1][1][0]=l[i]
        else:
            print('4구역 다참')
    #(2,0-1,y) 
    elif (l[i]%8)+1==5:
        if all(p[2,0,0:]==-100)==True:
            p[2][0][0]=l[i]
        elif p[2][0][1]==-100 and p[2][0][0]<=l[i]:
            p[2][0][1]=p[2][0][0]
            p[2][0][0]=l[i]
        elif p[2][0][2]==-100 and p[2][0][1]<=l[i]:
            p[2][0][2]=p[2][0][1]
            p[2][0][1]=p[2][0][0]
            p[2][0][0]=l[i]
        else:
            print('5구역 다참')
    elif (l[i]%8)+1==6:         
        if all(p[2,1,0:]==-100)==True:
            p[2][1][0]=l[i]
        elif p[2][1][1]==-100 and p[2][1][0]<=l[i]:
            p[2][1][1]=p[2][1][0]
            p[2][1][0]=l[i]
        elif p[2][1][2]==-100 and p[2][1][1]<=l[i]:
            p[2][1][2]=p[2][1][1]
            p[2][1][1]=p[2][1][0]
            p[2][1][0]=l[i]
        else:
            print('6구역 다참')
    #(3,0-1,y) 
    elif (l[i]%8)+1==7: 
        if all(p[3,0,0:]==-100)==True:
            p[3][0][0]=l[i]
        elif p[3][0][1]==-100 and p[3][0][0]<=l[i]:
            p[3][0][1]=p[3][0][0]
            p[3][0][0]=l[i]
        elif p[3][0][2]==-100 and p[2][0][1]<=l[i]:
            p[3][0][2]=p[3][0][1]
            p[3][0][1]=p[3][0][0]
            p[3][0][0]=l[i]
        else:
            print('7구역 다참')

    elif (l[i]%8)+1==8:   
        if all(p[3,1,0:]==-100)==True:
            p[3][1][0]=l[i]
        elif p[3][1][1]==-100 and p[3][1][0]<=l[i]:
            p[3][1][1]=p[3][1][0]
            p[3][1][0]=l[i]
        elif p[3][1][2]==-100 and p[3][1][1]<=l[i]:
            p[3][1][2]=p[3][1][1]
            p[3][1][1]=p[3][1][0]
            p[3][1][0]=l[i]
        else:
            print('8구역 다참')

print(p)

[[[   8. -100. -100.]
  [   9.    1. -100.]]

 [[  10.    2. -100.]
  [   3. -100. -100.]]

 [[   4. -100. -100.]
  [   5. -100. -100.]]

 [[   6. -100. -100.]
  [   7. -100. -100.]]]


In [6]:
print(p)
new(p,17)
print('--------------------------')
print(p)
# new(p,18)
# new(p,12)


[[[   8. -100. -100.]
  [   9.    1. -100.]]

 [[  10.    2. -100.]
  [   3. -100. -100.]]

 [[   4. -100. -100.]
  [   5. -100. -100.]]

 [[   6. -100. -100.]
  [   7. -100. -100.]]]
--------------------------
[[[   8. -100. -100.]
  [  17.    9.    1.]]

 [[  10.    2. -100.]
  [   3. -100. -100.]]

 [[   4. -100. -100.]
  [   5. -100. -100.]]

 [[   6. -100. -100.]
  [   7. -100. -100.]]]


In [7]:
re_array=p
print(type(re_array))
print(re_array)
re_array= re_array.tolist()

<class 'numpy.ndarray'>
[[[   8. -100. -100.]
  [  17.    9.    1.]]

 [[  10.    2. -100.]
  [   3. -100. -100.]]

 [[   4. -100. -100.]
  [   5. -100. -100.]]

 [[   6. -100. -100.]
  [   7. -100. -100.]]]


In [8]:
print(type(re_array))
print(re_array)

<class 'list'>
[[[8.0, -100.0, -100.0], [17.0, 9.0, 1.0]], [[10.0, 2.0, -100.0], [3.0, -100.0, -100.0]], [[4.0, -100.0, -100.0], [5.0, -100.0, -100.0]], [[6.0, -100.0, -100.0], [7.0, -100.0, -100.0]]]


# RDS insert

In [9]:
db=pymysql.connect(host="database-hanium.cijeogglkrqn.ap-northeast-2.rds.amazonaws.com", user="admin",password="gksdldma1234!")


In [10]:
cursor = db.cursor()
cursor

In [11]:
cursor.execute("select version()")


1

In [12]:
data = cursor.fetchone()

In [13]:
data #data version 확인

('10.5.9-MariaDB-log',)

In [14]:
# sql = '''create database sortedcon'''
# cursor.execute(sql)

In [ ]:
# sql = '''drop database sortedcon'''
# cursor.execute(sql)

In [67]:
# cursor.connection.commit()

In [15]:
# sql = '''use sortedcon'''
# cursor.execute(sql)

In [16]:
# sql = '''
# create table containerdate (
# id int not null auto_increment,
# primary key (id)
# )
# '''
# cursor.execute(sql)

## 필요하다면 참고 코드 (차원축소)

In [ ]:
# a2d=p.reshape(-1,2)# a2d는 차원을 2차원으로 줄인 배열
# print(a2d)
# re=a2d.reshape(4,2,3)#다시 변환해
# print(re)
