In [1]:
import random
import datetime
import numpy as np
import copy
from datetime import datetime, timedelta
import pandas as pd

In [2]:
#a=datetime.today() - timedelta(i)#+사전 컨테이너 레이블링
#b=a.strftime('%d') 
# #dictionary = dict(zip(l,r))
# #print(dictionary)

In [44]:
def new(array,date):
    p=array
    b=(date%8)+1
    if b==1:
        if all(p[0,0,0:]==-100)==True:
            p[0][0][0]=date
        elif p[0][0][1]==-100:
            if p[0][0][0]<=date:
                p[0][0][1]=p[0][0][0]
                p[0][0][0]=date
            
            elif p[0][0][0]>date:
                p[0][0][1]=date

        elif p[0][0][2]==-100:
           
            if p[0][0][1]>=date:
                p[0][0][2]=date 
            
            elif p[0][0][1]>date and p[0][0][0]<date:
                p[0][0][2]=p[0][0][1]
                p[0][0][1]=date
            elif p[0][0][0]<=date:
                p[0][0][2]=p[0][0][1]
                p[0][0][1]=p[0][0][0]
                p[0][0][0]=date
                
        else:
            b=b+1
            print('1구역 다참')
            

    elif b==2:
        if all(p[0,1,0:]==-100)==True:
            p[0][1][0]=date
        elif p[0][1][1]==-100:
            if p[0][1][0]<=date:
                p[0][1][1]=p[0][1][0]
                p[0][1][0]=date
            
            elif p[0][1][0]>date:
                p[0][1][1]=date

        elif p[0][1][2]==-100:
           
            if p[0][1][1]>=date:
                p[0][1][2]=date 
            
            elif p[0][1][1]>date and p[0][1][0]<date:
                p[0][1][2]=p[0][1][1]
                p[0][1][1]=date
            elif p[0][1][0]<=date:
                p[0][1][2]=p[0][1][1]
                p[0][1][1]=p[0][1][0]
                p[0][1][0]=date
        else:
            print('2구역 다참')
            
       
        #(1,0-1,y)       
    elif b==3:
        if all(p[1,0,0:]==-100)==True:
            p[1][0][0]=date
        elif p[1][0][1]==-100:
            if p[1][0][0]<=date:
                p[1][0][1]=p[1][0][0]
                p[1][0][0]=date
            
            elif p[1][0][0]>date:
                p[1][0][1]=date

        elif p[1][0][2]==-100:
           
            if p[1][0][1]>=date:
                p[1][0][2]=date 
        
            elif p[1][0][1]>date and p[1][0][0]<date:
                p[1][0][2]=p[1][0][1]
                p[1][0][1]=date
            elif p[1][0][0]<=date:
                p[1][0][2]=p[1][0][1]
                p[1][0][1]=p[1][0][0]
                p[1][0][0]=date
                
        else:
            print('3구역 다참')
            


    elif b==4:
        if all(p[1,1,0:]==-100)==True:
            p[1][1][0]=date
        elif p[1][1][1]==-100:
            if p[1][1][0]<=date:
                p[1][1][1]=p[1][1][0]
                p[1][1][0]=date
            
            elif p[1][1][0]>date:
                p[1][1][1]=date

        elif p[1][1][2]==-100:
           
            if p[1][1][1]>=date:
                p[1][1][2]=date 
            
            elif p[1][1][1]>date and p[1][1][0]<date:
                p[1][1][2]=p[1][1][1]
                p[1][1][1]=date
            elif p[1][1][0]<=date:
                p[1][1][2]=p[1][1][1]
                p[1][1][1]=p[1][1][0]
                p[1][1][0]=date
                
        else:
            
            print('4구역 다참')
            
    #(2,0-1,y) 
    elif b==5:
        if all(p[2,0,0:]==-100)==True:
            p[2][0][0]=date
        elif p[2][0][1]==-100:
            if p[2][0][0]<=date:
                p[2][0][1]=p[2][0][0]
                p[2][0][0]=date
            
            elif p[2][0][0]>date:
                p[2][0][1]=date

        elif p[2][0][2]==-100:
           
            if p[2][0][1]>=date:
                p[2][0][2]=date 
            
            elif p[2][0][1]>date and p[2][0][0]<date:
                p[2][0][2]=p[2][0][1]
                p[2][0][1]=date
            elif p[2][0][0]<=date:
                p[2][0][2]=p[2][0][1]
                p[2][0][1]=p[2][0][0]
                p[2][0][0]=date
                
        else:
            print('5구역 다참')
            

        
        
    elif b==6:         
        if all(p[2,1,0:]==-100)==True:
            p[2][1][0]=date
        elif p[2][1][1]==-100:
            if p[2][1][0]<=date:
                p[2][1][1]=p[2][1][0]
                p[2][1][0]=date
            
            elif p[2][1][0]>date:
                p[2][1][1]=date

        elif p[2][1][2]==-100:
           
            if p[2][1][1]>=date:
                p[2][1][2]=date 
            
            elif p[2][1][1]>date and p[2][1][0]<date:
                p[2][1][2]=p[2][1][1]
                p[2][1][1]=date
            elif p[2][1][0]<=date:
                p[2][1][2]=p[2][1][1]
                p[2][1][1]=p[2][1][0]
                p[2][1][0]=date
                
        else:
            print('6구역 다참')
           
        #(3,0-1,y) 
    elif b==7:
        if all(p[3,0,0:]==-100)==True:
            p[3][0][0]=date
        elif p[3][0][1]==-100:
            if p[3][0][0]<=date:
                p[3][0][1]=p[3][0][0]
                p[3][0][0]=date
            
            elif p[3][0][0]>date:
                p[3][0][1]=date

        elif p[3][0][2]==-100:
           
            if p[3][0][1]>=date:
                p[3][0][2]=date 
            
            elif p[3][0][1]>date and p[3][0][0]<date:
                p[3][0][2]=p[3][0][1]
                p[3][0][1]=date
            elif p[3][0][0]<=date:
                p[3][0][2]=p[3][0][1]
                p[3][0][1]=p[3][0][0]
                p[3][0][0]=date
                
        else:
            print('7구역 다참')
            

    elif b==8:
        if all(p[3,1,0:]==-100)==True:
            p[3][1][0]=date
        elif p[3][1][1]==-100:
            if p[3][1][0]<=date:
                p[3][1][1]=p[3][1][0]
                p[3][1][0]=date
            
            elif p[3][1][0]>date:
                p[3][1][1]=date

        elif p[3][1][2]==-100:
           
            if p[3][1][1]>=date:
                p[3][1][2]=date 
            
            elif p[3][1][1]>date and p[3][1][0]<date:
                p[3][1][2]=p[3][1][1]
                p[3][1][1]=date
            elif p[3][1][0]<=date:
                p[3][1][2]=p[3][1][1]
                p[3][1][1]=p[3][1][0]
                p[3][1][0]=date
                
        else:
            print('8구역 다참')
           
            
        
    return array

SyntaxError: 'continue' not properly in loop (<ipython-input-44-ed104486cec3>, line 31)

In [10]:
l=[] #원래 컨테이너 빼는 날짜
p=np.zeros([4,2,3])-100
for i in range(10):#length(컨테이너개수)
    l.append(i+1)
    
for i in range(14):#24-length
    l.append(-100)
    
l.sort()
print(l)

[-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [41]:
p=np.zeros([4,2,3])-100

for i in range(24):
    if l[i]==-100:
        continue 
    #(0,0-1,y)
    elif (l[i]%8)+1==1:
        if all(p[0,0,0:]==-100)==True:
            p[0][0][0]=l[i]
        elif p[0][0][1]==-100 and p[0][0][0]<=l[i]:
            p[0][0][1]=p[0][0][0]
            p[0][0][0]=l[i]

        elif p[0][0][2]==-100 and p[0][0][1]<=l[i]:
            p[0][0][2]=p[0][0][1]
            p[0][0][1]=p[0][0][0]
            p[0][0][0]=l[i]
        else:
            print('1구역 다참')

    elif (l[i]%8)+1==2:
        if all(p[0,1,0:]==-100)==True:
            p[0][1][0]=l[i]
        elif p[0][1][1]==-100 and p[0][1][0]<=l[i]:
            p[0][1][1]=p[0][1][0]
            p[0][1][0]=l[i]
        elif p[0][1][2]==-100 and p[0][1][1]<=l[i]:
            p[0][1][2]=p[0][1][1]
            p[0][1][1]=p[0][1][0]
            p[0][1][0]=l[i]
        else:
            print('2구역 다참')
    #(1,0-1,y)       
    elif (l[i]%8)+1==3:
        if all(p[1,0,0:]==-100)==True:
            p[1][0][0]=l[i]
        elif p[1][0][1]==-100 and p[1][0][0]<=l[i]:
            p[1][0][1]=p[1][0][0]
            p[1][0][0]=l[i]
        elif p[1][0][2]==-100 and p[1][0][1]<=l[i]:
            p[1][0][2]=p[1][0][1]
            p[1][0][1]=p[1][0][0]
            p[1][0][0]=l[i]
        else:
            print('3구역 다참')

    elif (l[i]%8)+1==4:
        if all(p[1,1,0:]==-100)==True:
            p[1][1][0]=l[i]
        elif p[1][1][1]==-100 and p[1][1][0]<=l[i]:
            p[1][1][1]=p[1][1][0]
            p[1][1][0]=l[i]
        elif p[1][1][2]==-100 and p[1][1][1]<=l[i]:
            p[1][1][2]=p[1][1][1]
            p[1][1][1]=p[1][1][0]
            p[1][1][0]=l[i]
        else:
            print('4구역 다참')
    #(2,0-1,y) 
    elif (l[i]%8)+1==5:
        if all(p[2,0,0:]==-100)==True:
            p[2][0][0]=l[i]
        elif p[2][0][1]==-100 and p[2][0][0]<=l[i]:
            p[2][0][1]=p[2][0][0]
            p[2][0][0]=l[i]
        elif p[2][0][2]==-100 and p[2][0][1]<=l[i]:
            p[2][0][2]=p[2][0][1]
            p[2][0][1]=p[2][0][0]
            p[2][0][0]=l[i]
        else:
            print('5구역 다참')
    elif (l[i]%8)+1==6:         
        if all(p[2,1,0:]==-100)==True:
            p[2][1][0]=l[i]
        elif p[2][1][1]==-100 and p[2][1][0]<=l[i]:
            p[2][1][1]=p[2][1][0]
            p[2][1][0]=l[i]
        elif p[2][1][2]==-100 and p[2][1][1]<=l[i]:
            p[2][1][2]=p[2][1][1]
            p[2][1][1]=p[2][1][0]
            p[2][1][0]=l[i]
        else:
            print('6구역 다참')
    #(3,0-1,y) 
    elif (l[i]%8)+1==7: 
        if all(p[3,0,0:]==-100)==True:
            p[3][0][0]=l[i]
        elif p[3][0][1]==-100 and p[3][0][0]<=l[i]:
            p[3][0][1]=p[3][0][0]
            p[3][0][0]=l[i]
        elif p[3][0][2]==-100 and p[2][0][1]<=l[i]:
            p[3][0][2]=p[3][0][1]
            p[3][0][1]=p[3][0][0]
            p[3][0][0]=l[i]
        else:
            print('7구역 다참')

    elif (l[i]%8)+1==8:   
        if all(p[3,1,0:]==-100)==True:
            p[3][1][0]=l[i]
        elif p[3][1][1]==-100 and p[3][1][0]<=l[i]:
            p[3][1][1]=p[3][1][0]
            p[3][1][0]=l[i]
        elif p[3][1][2]==-100 and p[3][1][1]<=l[i]:
            p[3][1][2]=p[3][1][1]
            p[3][1][1]=p[3][1][0]
            p[3][1][0]=l[i]
        else:
            print('8구역 다참')

print(p)

[[[   8. -100. -100.]
  [   9.    1. -100.]]

 [[  10.    2. -100.]
  [   3. -100. -100.]]

 [[   4. -100. -100.]
  [   5. -100. -100.]]

 [[   6. -100. -100.]
  [   7. -100. -100.]]]


In [42]:
print(p)
new(p,0)
# new(p,18)
# new(p,12)


[[[   8. -100. -100.]
  [   9.    1. -100.]]

 [[  10.    2. -100.]
  [   3. -100. -100.]]

 [[   4. -100. -100.]
  [   5. -100. -100.]]

 [[   6. -100. -100.]
  [   7. -100. -100.]]]


array([[[   8.,    0., -100.],
        [   9.,    1., -100.]],

       [[  10.,    2., -100.],
        [   3., -100., -100.]],

       [[   4., -100., -100.],
        [   5., -100., -100.]],

       [[   6., -100., -100.],
        [   7., -100., -100.]]])