In [154]:
import heapq
import random
import datetime
import numpy as np
import copy
from datetime import datetime, timedelta

[1, 2, 3, 4, 5]


In [163]:
#날짜 순 
#출고날짜와 컨테이너 라벨링링을 합침(컨테이너 라벨링은 리스트로 되어있음)
#정렬된 heap에서 정렬하면 끝!
p=[]
for i in range(20):#length(컨테이너개수)
    a=datetime.today() - timedelta(i)#+사전 컨테이너 레이블링
    b=a.strftime('%Y%m%d') 
    b=int(b)
    p.append(b)
    
for i in range(4):#24-length
    p.append(0)

p.sort()
print(p)

p=np.array(p)
b=p.reshape(2,3,4)
print(b)
print(b[0][1][1])
#예외 제일최근 날짜인데 빈공간있으면 그곳으로 넣는게 이득


[0, 0, 0, 0, 20210701, 20210702, 20210703, 20210704, 20210705, 20210706, 20210707, 20210708, 20210709, 20210710, 20210711, 20210712, 20210713, 20210714, 20210715, 20210716, 20210717, 20210718, 20210719, 20210720]
[[[       0        0        0        0]
  [20210701 20210702 20210703 20210704]
  [20210705 20210706 20210707 20210708]]

 [[20210709 20210710 20210711 20210712]
  [20210713 20210714 20210715 20210716]
  [20210717 20210718 20210719 20210720]]]
20210702


In [168]:
#히프로받아서 3차원배열로 변환후 
heap=[]
for i in range(20):#length(컨테이너개수)
    a=datetime.today() - timedelta(i)#+사전 컨테이너 레이블링
    b=a.strftime('%Y%m%d') 
    b=int(b)
    heapq.heappush(heap,b)
    
for i in range(4):#24-length
    heapq.heappush(heap,0)
print(heap)
a=np.array(heap)
b=a.reshape(2,3,4)
print(b)

[0, 0, 0, 20210704, 0, 20210707, 20210708, 20210711, 20210705, 20210703, 20210701, 20210710, 20210715, 20210716, 20210709, 20210720, 20210714, 20210717, 20210706, 20210718, 20210712, 20210713, 20210702, 20210719]
[[[       0        0        0 20210704]
  [       0 20210707 20210708 20210711]
  [20210705 20210703 20210701 20210710]]

 [[20210715 20210716 20210709 20210720]
  [20210714 20210717 20210706 20210718]
  [20210712 20210713 20210702 20210719]]]
