In [87]:
import random
import datetime
import numpy as np
import copy
from datetime import datetime, timedelta
import pandas as pd

In [100]:
# p=np.zeros([4,2,3])
# l=[] #원래 컨테이너 빼는 날짜
# r=[0 for i in range(24)]
# for i in range(10):#length(컨테이너개수)
#     #a=datetime.today() - timedelta(i)#+사전 컨테이너 레이블링
#     #b=a.strftime('%d') 
#     l.append(random.randint(1,30))
    
# for i in range(14):#24-length
#     l.append(0)

# l.sort()
# print(l)
# #b=np.array(l)
# #c=b.reshape(4,2,3)
# # for i in range(24):
# #     if l[i]==0:
# #         r[i]=0
# #     else:
# #         r[i]=(l[i]%8)+1
# # print(r)
# #dictionary = dict(zip(l,r))
# #print(dictionary)
# for i in range(24):
#     if l[i]==0:
#         continue
#     elif (l[i]%8)+1==1:

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 10, 13, 17, 18, 23, 23, 24, 28, 30]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 3, 6, 2, 3, 8, 8, 1, 5, 7]
{0: 0, 4: 5, 10: 3, 13: 6, 17: 2, 18: 3, 23: 8, 24: 1, 28: 5, 30: 7}


In [122]:
p=np.zeros([4,2,3])
print(p)
l=[] #원래 컨테이너 빼는 날짜
for i in range(10):#length(컨테이너개수)
    l.append(random.randint(1,30))
    
for i in range(14):#24-length
    l.append(0)
    
l.sort()
print(l)
print('------------------------------------------')

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 6, 8, 10, 13, 15, 18, 26, 26, 29]
------------------------------------------


In [123]:
for i in range(24):
    if l[i]==0:
        continue 
    #(0,0-1,y)
    elif (l[i]%8)+1==1:
        if all(p[0,0,0:2])==0:
            p[0][0][0]=l[i]
        
    elif (l[i]%8)+1==2:
        if all(p[0,1,0:2])==0:
            p[0][1][0]=l[i]
    #(1,0-1,y)       
    elif (l[i]%8)+1==3:
        if all(p[1,0,0:2])==0:
            p[1][0][0]=l[i]
            
    elif (l[i]%8)+1==4:
        if all(p[1,1,0:2])==0:
            p[1][1][0]=l[i]
    #(2,0-1,y) 
    elif (l[i]%8)+1==5:
        if all(p[2,0,0:2])==0:
            p[2][0][0]=l[i]
    elif (l[i]%8)+1==6:         
        if all(p[2,1,0:2])==0:
            p[2][1][0]=l[i]
    #(3,0-1,y) 
    elif (l[i]%8)+1==7: 
        if all(p[3,0,0:2])==0:
            p[3][0][0]=l[i]
            
    elif (l[i]%8)+1==8:   
        if all(p[3,1,0:2])==0:
            p[3][1][0]=l[i]
            
print(p)
        

[[[ 8.  0.  0.]
  [ 0.  0.  0.]]

 [[26.  0.  0.]
  [ 3.  0.  0.]]

 [[ 0.  0.  0.]
  [29.  0.  0.]]

 [[ 6.  0.  0.]
  [15.  0.  0.]]]
