In [1]:
import random
import datetime
import numpy as np
import copy
from datetime import datetime, timedelta
import pandas as pd

In [2]:
#a=datetime.today() - timedelta(i)#+사전 컨테이너 레이블링
#b=a.strftime('%d') 
# #dictionary = dict(zip(l,r))
# #print(dictionary)

In [17]:
l=[] #원래 컨테이너 빼는 날짜
for i in range(23):#length(컨테이너개수)
    l.append(i+1)
    
for i in range(1):#24-length
    l.append(-100)
    
l.sort()
print(l)



[-100, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]


In [19]:
p=np.zeros([4,2,3])-100
for i in range(24):
    if l[i]==-100:
        continue 
    #(0,0-1,y)
    elif (l[i]%8)+1==1:
        if all(p[0,0,0:]==-100)==True:
            p[0][0][0]=l[i]
        elif p[0][0][1]==-100 and p[0][0][0]<=l[i]:
            p[0][0][1]=p[0][0][0]
            p[0][0][0]=l[i]
        
        elif p[0][0][2]==-100 and p[0][0][1]<=l[i]:
            p[0][0][2]=p[0][0][1]
            p[0][0][1]=p[0][0][0]
            p[0][0][0]=l[i]
        else:
            print('1구역 다참')
                    
    elif (l[i]%8)+1==2:
        if all(p[0,1,0:]==-100)==True:
            p[0][1][0]=l[i]
        elif p[0][1][1]==-100 and p[0][1][0]<=l[i]:
            p[0][1][1]=p[0][1][0]
            p[0][1][0]=l[i]
        elif p[0][1][2]==-100 and p[0][1][1]<=l[i]:
            p[0][1][2]=p[0][1][1]
            p[0][1][1]=p[0][1][0]
            p[0][1][0]=l[i]
        else:
            print('2구역 다참')
    #(1,0-1,y)       
    elif (l[i]%8)+1==3:
        if all(p[1,0,0:]==-100)==True:
            p[1][0][0]=l[i]
        elif p[1][0][1]==-100 and p[1][0][0]<=l[i]:
            p[1][0][1]=p[1][0][0]
            p[1][0][0]=l[i]
        elif p[1][0][2]==-100 and p[1][0][1]<=l[i]:
            p[1][0][2]=p[1][0][1]
            p[1][0][1]=p[1][0][0]
            p[1][0][0]=l[i]
        else:
            print('3구역 다참')
            
    elif (l[i]%8)+1==4:
        if all(p[1,1,0:]==-100)==True:
            p[1][1][0]=l[i]
        elif p[1][1][1]==-100 and p[1][1][0]<=l[i]:
            p[1][1][1]=p[1][1][0]
            p[1][1][0]=l[i]
        elif p[1][1][2]==-100 and p[1][1][1]<=l[i]:
            p[1][1][2]=p[1][1][1]
            p[1][1][1]=p[1][1][0]
            p[1][1][0]=l[i]
        else:
            print('4구역 다참')
    #(2,0-1,y) 
    elif (l[i]%8)+1==5:
        if all(p[2,0,0:]==-100)==True:
            p[2][0][0]=l[i]
        elif p[2][0][1]==-100 and p[2][0][0]<=l[i]:
            p[2][0][1]=p[2][0][0]
            p[2][0][0]=l[i]
        elif p[2][0][2]==-100 and p[2][0][1]<=l[i]:
            p[2][0][2]=p[2][0][1]
            p[2][0][1]=p[2][0][0]
            p[2][0][0]=l[i]
        else:
            print('5구역 다참')
    elif (l[i]%8)+1==6:         
        if all(p[2,1,0:]==-100)==True:
            p[2][1][0]=l[i]
        elif p[2][1][1]==-100 and p[2][1][0]<=l[i]:
            p[2][1][1]=p[2][1][0]
            p[2][1][0]=l[i]
        elif p[2][1][2]==-100 and p[2][1][1]<=l[i]:
            p[2][1][2]=p[2][1][1]
            p[2][1][1]=p[2][1][0]
            p[2][1][0]=l[i]
        else:
            print('6구역 다참')
    #(3,0-1,y) 
    elif (l[i]%8)+1==7: 
        if all(p[3,0,0:]==-100)==True:
            p[3][0][0]=l[i]
        elif p[3][0][1]==-100 and p[3][0][0]<=l[i]:
            p[3][0][1]=p[3][0][0]
            p[3][0][0]=l[i]
        elif p[3][0][2]==-100 and p[2][0][1]<=l[i]:
            p[3][0][2]=p[3][0][1]
            p[3][0][1]=p[3][0][0]
            p[3][0][0]=l[i]
        else:
            print('7구역 다참')
            
    elif (l[i]%8)+1==8:   
        if all(p[3,1,0:]==-100)==True:
            p[3][1][0]=l[i]
        elif p[3][1][1]==-100 and p[3][1][0]<=l[i]:
            p[3][1][1]=p[3][1][0]
            p[3][1][0]=l[i]
        elif p[3][1][2]==-100 and p[3][1][1]<=l[i]:
            p[3][1][2]=p[3][1][1]
            p[3][1][1]=p[3][1][0]
            p[3][1][0]=l[i]
        else:
            print('8구역 다참')
            
print(p)

[[[  16.    8. -100.]
  [  17.    9.    1.]]

 [[  18.   10.    2.]
  [  19.   11.    3.]]

 [[  20.   12.    4.]
  [  21.   13.    5.]]

 [[  22.   14.    6.]
  [  23.   15.    7.]]]
