In [1]:
import random
import datetime
import numpy as np
import copy
from datetime import datetime, timedelta
import pymysql


In [2]:
#a=datetime.today() - timedelta(i)#+사전 컨테이너 레이블링
#b=a.strftime('%d') 
# #dictionary = dict(zip(l,r))
# #print(dictionary)

In [3]:
#!pip install PyMySQL

In [4]:
def rest1(array,date):
    p=array
    if all(p[0,0,0:]==0)==True:
        p[0][0][0]=date
    elif p[0][0][1]==0:
        if p[0][0][0]<=date:
            p[0][0][1]=p[0][0][0]
            p[0][0][0]=date

        elif p[0][0][0]>date:
            p[0][0][1]=date

    elif p[0][0][2]==0:

        if p[0][0][1]>=date:
            p[0][0][2]=date 

        elif p[0][0][1]<date and p[0][0][0]>date:
            p[0][0][2]=p[0][0][1]
            p[0][0][1]=date
        elif p[0][0][0]<=date:
            p[0][0][2]=p[0][0][1]
            p[0][0][1]=p[0][0][0]
            p[0][0][0]=date

    else:
        rest2(p,date)
    return array

def rest2(array,date):
    p=array  
    if all(p[0,1,0:]==0)==True:
        p[0][1][0]=date
    elif p[0][1][1]==0:
        if p[0][1][0]<=date:
            p[0][1][1]=p[0][1][0]
            p[0][1][0]=date

        elif p[0][1][0]>date:
            p[0][1][1]=date

    elif p[0][1][2]==0:

        if p[0][1][1]>=date:
            p[0][1][2]=date 

        elif p[0][1][1]<date and p[0][1][0]>date:
            p[0][1][2]=p[0][1][1]
            p[0][1][1]=date
        elif p[0][1][0]<=date:
            p[0][1][2]=p[0][1][1]
            p[0][1][1]=p[0][1][0]
            p[0][1][0]=date
    else:
        print('2구역 다참')
        rest3(p,date)
    return array

def rest3(array,date):
    p=array
    if all(p[1,0,0:]==0)==True:
        p[1][0][0]=date
    elif p[1][0][1]==0:
        if p[1][0][0]<=date:
            p[1][0][1]=p[1][0][0]
            p[1][0][0]=date

        elif p[1][0][0]>date:
            p[1][0][1]=date

    elif p[1][0][2]==0:

        if p[1][0][1]>=date:
            p[1][0][2]=date 

        elif p[1][0][1]<date and p[1][0][0]>date:
            p[1][0][2]=p[1][0][1]
            p[1][0][1]=date
        elif p[1][0][0]<=date:
            p[1][0][2]=p[1][0][1]
            p[1][0][1]=p[1][0][0]
            p[1][0][0]=date

    else:
        print('3구역 다참')
        rest4(p,date)
    return array

def rest4(array,date):
    p=array
    if all(p[1,1,0:]==0)==True:
        p[1][1][0]=date
    elif p[1][1][1]==0:
        if p[1][1][0]<=date:
            p[1][1][1]=p[1][1][0]
            p[1][1][0]=date

        elif p[1][1][0]>date:
            p[1][1][1]=date

    elif p[1][1][2]==0:

        if p[1][1][1]>=date:
            p[1][1][2]=date 

        elif p[1][1][1]<date and p[1][1][0]>date:
            p[1][1][2]=p[1][1][1]
            p[1][1][1]=date
        elif p[1][1][0]<=date:
            p[1][1][2]=p[1][1][1]
            p[1][1][1]=p[1][1][0]
            p[1][1][0]=date

    else:
        print('4구역 다참')
        rest5(p,date)
            
    return array

def rest5(array,date):
    p=array
    if all(p[2,0,0:]==0)==True:
        p[2][0][0]=date
    elif p[2][0][1]==0:
        if p[2][0][0]<=date:
            p[2][0][1]=p[2][0][0]
            p[2][0][0]=date

        elif p[2][0][0]>date:
            p[2][0][1]=date

    elif p[2][0][2]==0:

        if p[2][0][1]>=date:
            p[2][0][2]=date 

        elif p[2][0][1]<date and p[2][0][0]>date:
            p[2][0][2]=p[2][0][1]
            p[2][0][1]=date
        elif p[2][0][0]<=date:
            p[2][0][2]=p[2][0][1]
            p[2][0][1]=p[2][0][0]
            p[2][0][0]=date

    else:
        print('5구역 다참')
        rest6(p,date)
            
    return array

def rest6(array,date):
    p=array     
    if all(p[2,1,0:]==0)==True:
        p[2][1][0]=date
    elif p[2][1][1]==0:
        if p[2][1][0]<=date:
            p[2][1][1]=p[2][1][0]
            p[2][1][0]=date

        elif p[2][1][0]>date:
            p[2][1][1]=date

    elif p[2][1][2]==0:

        if p[2][1][1]>=date:
            p[2][1][2]=date 

        elif p[2][1][1]<date and p[2][1][0]>date:
            p[2][1][2]=p[2][1][1]
            p[2][1][1]=date
        elif p[2][1][0]<=date:
            p[2][1][2]=p[2][1][1]
            p[2][1][1]=p[2][1][0]
            p[2][1][0]=date

    else:
        print('6구역 다참')
        rest7(array,date)
    return array

def rest7(array,date):
    p=array 
    if all(p[3,0,0:]==0)==True:
        p[3][0][0]=date
    elif p[3][0][1]==0:
        if p[3][0][0]<=date:
            p[3][0][1]=p[3][0][0]
            p[3][0][0]=date

        elif p[3][0][0]>date:
            p[3][0][1]=date

    elif p[3][0][2]==0:

        if p[3][0][1]>=date:
            p[3][0][2]=date 

        elif p[3][0][1]<date and p[3][0][0]>date:
            p[3][0][2]=p[3][0][1]
            p[3][0][1]=date
        elif p[3][0][0]<=date:
            p[3][0][2]=p[3][0][1]
            p[3][0][1]=p[3][0][0]
            p[3][0][0]=date

    else:
        print('7구역 다참')
        rest8(p,date)
    return array

def rest8(array,date):
    p=array 
    if all(p[3,1,0:]==0)==True:
        p[3][1][0]=date
    elif p[3][1][1]==0:
        if p[3][1][0]<=date:
            p[3][1][1]=p[3][1][0]
            p[3][1][0]=date

        elif p[3][1][0]>date:
            p[3][1][1]=date

    elif p[3][1][2]==0:

        if p[3][1][1]>=date:
            p[3][1][2]=date 

        elif p[3][1][1]<date and p[3][1][0]>date:
            p[3][1][2]=p[3][1][1]
            p[3][1][1]=date
        elif p[3][1][0]<=date:
            p[3][1][2]=p[3][1][1]
            p[3][1][1]=p[3][1][0]
            p[3][1][0]=date

    else:
        print('8구역 다참')
        rest1(array,date)
    return array  

In [5]:
def new(array,date):
    p=array
    b=(date%8)+1
    if b==1:
        if all(p[0,0,0:]==0)==True:
            p[0][0][0]=date
        elif p[0][0][1]==0:
            if p[0][0][0]<=date:
                p[0][0][1]=p[0][0][0]
                p[0][0][0]=date
            
            elif p[0][0][0]>date:
                p[0][0][1]=date

        elif p[0][0][2]==0:
           
            if p[0][0][1]>=date:
                p[0][0][2]=date 
            
            elif p[0][0][1]<date and p[0][0][0]>date:
                p[0][0][2]=p[0][0][1]
                p[0][0][1]=date
            elif p[0][0][0]<=date:
                p[0][0][2]=p[0][0][1]
                p[0][0][1]=p[0][0][0]
                p[0][0][0]=date
                
        else:
            print('1구역 다참')
            rest2(p,date)
            

    elif b==2:
        if all(p[0,1,0:]==0)==True:
            p[0][1][0]=date
        elif p[0][1][1]==0:
            if p[0][1][0]<=date:
                p[0][1][1]=p[0][1][0]
                p[0][1][0]=date
            
            elif p[0][1][0]>date:
                p[0][1][1]=date

        elif p[0][1][2]==0:
           
            if p[0][1][1]>=date:
                p[0][1][2]=date 
            
            elif p[0][1][1]<date and p[0][1][0]>date:
                p[0][1][2]=p[0][1][1]
                p[0][1][1]=date
            elif p[0][1][0]<=date:
                p[0][1][2]=p[0][1][1]
                p[0][1][1]=p[0][1][0]
                p[0][1][0]=date
        else:
            print('2구역 다참')
            rest3(p,date)
            
       
        #(1,0-1,y)       
    elif b==3:
        if all(p[1,0,0:]==0)==True:
            p[1][0][0]=date
        elif p[1][0][1]==0:
            if p[1][0][0]<=date:
                p[1][0][1]=p[1][0][0]
                p[1][0][0]=date
            
            elif p[1][0][0]>date:
                p[1][0][1]=date

        elif p[1][0][2]==0:
           
            if p[1][0][1]>=date:
                p[1][0][2]=date 
        
            elif p[1][0][1]<date and p[1][0][0]>date:
                p[1][0][2]=p[1][0][1]
                p[1][0][1]=date
            elif p[1][0][0]<=date:
                p[1][0][2]=p[1][0][1]
                p[1][0][1]=p[1][0][0]
                p[1][0][0]=date
                
        else:
            print('3구역 다참')
            rest4(p,date)
            


    elif b==4:
        if all(p[1,1,0:]==0)==True:
            p[1][1][0]=date
        elif p[1][1][1]==0:
            if p[1][1][0]<=date:
                p[1][1][1]=p[1][1][0]
                p[1][1][0]=date
            
            elif p[1][1][0]>date:
                p[1][1][1]=date

        elif p[1][1][2]==0:
           
            if p[1][1][1]>=date:
                p[1][1][2]=date 
            
            elif p[1][1][1]<date and p[1][1][0]>date:
                p[1][1][2]=p[1][1][1]
                p[1][1][1]=date
            elif p[1][1][0]<=date:
                p[1][1][2]=p[1][1][1]
                p[1][1][1]=p[1][1][0]
                p[1][1][0]=date
                
        else:
            print('4구역 다참')
            rest5(p,date)
            
    #(2,0-1,y) 
    elif b==5:
        if all(p[2,0,0:]==-0)==True:
            p[2][0][0]=date
        elif p[2][0][1]==0:
            if p[2][0][0]<=date:
                p[2][0][1]=p[2][0][0]
                p[2][0][0]=date
            
            elif p[2][0][0]>date:
                p[2][0][1]=date

        elif p[2][0][2]==0:
           
            if p[2][0][1]>=date:
                p[2][0][2]=date 
            
            elif p[2][0][1]<date and p[2][0][0]>date:
                p[2][0][2]=p[2][0][1]
                p[2][0][1]=date
            elif p[2][0][0]<=date:
                p[2][0][2]=p[2][0][1]
                p[2][0][1]=p[2][0][0]
                p[2][0][0]=date
                
        else:
            print('5구역 다참')
            rest6(p,date)
            

        
        
    elif b==6:         
        if all(p[2,1,0:]==0)==True:
            p[2][1][0]=date
        elif p[2][1][1]==0:
            if p[2][1][0]<=date:
                p[2][1][1]=p[2][1][0]
                p[2][1][0]=date
            
            elif p[2][1][0]>date:
                p[2][1][1]=date

        elif p[2][1][2]==0:
           
            if p[2][1][1]>=date:
                p[2][1][2]=date 
            
            elif p[2][1][1]<date and p[2][1][0]>date:
                p[2][1][2]=p[2][1][1]
                p[2][1][1]=date
            elif p[2][1][0]<=date:
                p[2][1][2]=p[2][1][1]
                p[2][1][1]=p[2][1][0]
                p[2][1][0]=date
                
        else:
            print('6구역 다참')
            rest7(p,date)
           
        #(3,0-1,y) 
    elif b==7:
        if all(p[3,0,0:]==0)==True:
            p[3][0][0]=date
        elif p[3][0][1]==0:
            if p[3][0][0]<=date:
                p[3][0][1]=p[3][0][0]
                p[3][0][0]=date
            
            elif p[3][0][0]>date:
                p[3][0][1]=date

        elif p[3][0][2]==0:
           
            if p[3][0][1]>=date:
                p[3][0][2]=date 
            
            elif p[3][0][1]<date and p[3][0][0]>date:
                p[3][0][2]=p[3][0][1]
                p[3][0][1]=date
            elif p[3][0][0]<=date:
                p[3][0][2]=p[3][0][1]
                p[3][0][1]=p[3][0][0]
                p[3][0][0]=date
                
        else:
            print('7구역 다참')
            rest8(p,date)
            

    elif b==8:
        if all(p[3,1,0:]==0)==True:
            p[3][1][0]=date
        elif p[3][1][1]==0:
            if p[3][1][0]<=date:
                p[3][1][1]=p[3][1][0]
                p[3][1][0]=date
            
            elif p[3][1][0]>date:
                p[3][1][1]=date

        elif p[3][1][2]==0:
           
            if p[3][1][1]>=date:
                p[3][1][2]=date 
            
            elif p[3][1][1]<date and p[3][1][0]>date:
                p[3][1][2]=p[3][1][1]
                p[3][1][1]=date
            elif p[3][1][0]<=date:
                p[3][1][2]=p[3][1][1]
                p[3][1][1]=p[3][1][0]
                p[3][1][0]=date
                
        else:
            print('8구역 다참')
            rest1(p,date)
           
            
        
    return array

In [6]:
l=[] #원래 컨테이너 빼는 날짜
for i in range(10):#length(컨테이너개수)
    l.append(i+1)
    
for i in range(14):#24-length
    l.append(0)
    
l.sort()
print(l)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [7]:
p=np.zeros([4,2,3])

for i in range(24):
    if l[i]==0:
        continue 
    #(0,0-1,y)
    elif (l[i]%8)+1==1:
        if all(p[0,0,0:]==0)==True:
            p[0][0][0]=l[i]
        elif p[0][0][1]==0 and p[0][0][0]<=l[i]:
            p[0][0][1]=p[0][0][0]
            p[0][0][0]=l[i]

        elif p[0][0][2]==0 and p[0][0][1]<=l[i]:
            p[0][0][2]=p[0][0][1]
            p[0][0][1]=p[0][0][0]
            p[0][0][0]=l[i]
        else:
            print('1구역 다참')

    elif (l[i]%8)+1==2:
        if all(p[0,1,0:]==0)==True:
            p[0][1][0]=l[i]
        elif p[0][1][1]==0 and p[0][1][0]<=l[i]:
            p[0][1][1]=p[0][1][0]
            p[0][1][0]=l[i]
        elif p[0][1][2]==0 and p[0][1][1]<=l[i]:
            p[0][1][2]=p[0][1][1]
            p[0][1][1]=p[0][1][0]
            p[0][1][0]=l[i]
        else:
            print('2구역 다참')
    #(1,0-1,y)       
    elif (l[i]%8)+1==3:
        if all(p[1,0,0:]==0)==True:
            p[1][0][0]=l[i]
        elif p[1][0][1]==0 and p[1][0][0]<=l[i]:
            p[1][0][1]=p[1][0][0]
            p[1][0][0]=l[i]
        elif p[1][0][2]==0 and p[1][0][1]<=l[i]:
            p[1][0][2]=p[1][0][1]
            p[1][0][1]=p[1][0][0]
            p[1][0][0]=l[i]
        else:
            print('3구역 다참')

    elif (l[i]%8)+1==4:
        if all(p[1,1,0:]==0)==True:
            p[1][1][0]=l[i]
        elif p[1][1][1]==0 and p[1][1][0]<=l[i]:
            p[1][1][1]=p[1][1][0]
            p[1][1][0]=l[i]
        elif p[1][1][2]==0 and p[1][1][1]<=l[i]:
            p[1][1][2]=p[1][1][1]
            p[1][1][1]=p[1][1][0]
            p[1][1][0]=l[i]
        else:
            print('4구역 다참')
    #(2,0-1,y) 
    elif (l[i]%8)+1==5:
        if all(p[2,0,0:]==0)==True:
            p[2][0][0]=l[i]
        elif p[2][0][1]==0 and p[2][0][0]<=l[i]:
            p[2][0][1]=p[2][0][0]
            p[2][0][0]=l[i]
        elif p[2][0][2]==0 and p[2][0][1]<=l[i]:
            p[2][0][2]=p[2][0][1]
            p[2][0][1]=p[2][0][0]
            p[2][0][0]=l[i]
        else:
            print('5구역 다참')
    elif (l[i]%8)+1==6:         
        if all(p[2,1,0:]==0)==True:
            p[2][1][0]=l[i]
        elif p[2][1][1]==0 and p[2][1][0]<=l[i]:
            p[2][1][1]=p[2][1][0]
            p[2][1][0]=l[i]
        elif p[2][1][2]==0 and p[2][1][1]<=l[i]:
            p[2][1][2]=p[2][1][1]
            p[2][1][1]=p[2][1][0]
            p[2][1][0]=l[i]
        else:
            print('6구역 다참')
    #(3,0-1,y) 
    elif (l[i]%8)+1==7: 
        if all(p[3,0,0:]==0)==True:
            p[3][0][0]=l[i]
        elif p[3][0][1]==0 and p[3][0][0]<=l[i]:
            p[3][0][1]=p[3][0][0]
            p[3][0][0]=l[i]
        elif p[3][0][2]==0 and p[2][0][1]<=l[i]:
            p[3][0][2]=p[3][0][1]
            p[3][0][1]=p[3][0][0]
            p[3][0][0]=l[i]
        else:
            print('7구역 다참')

    elif (l[i]%8)+1==8:   
        if all(p[3,1,0:]==0)==True:
            p[3][1][0]=l[i]
        elif p[3][1][1]==0 and p[3][1][0]<=l[i]:
            p[3][1][1]=p[3][1][0]
            p[3][1][0]=l[i]
        elif p[3][1][2]==0 and p[3][1][1]<=l[i]:
            p[3][1][2]=p[3][1][1]
            p[3][1][1]=p[3][1][0]
            p[3][1][0]=l[i]
        else:
            print('8구역 다참')

print(p)

[[[ 8.  0.  0.]
  [ 9.  1.  0.]]

 [[10.  2.  0.]
  [ 3.  0.  0.]]

 [[ 4.  0.  0.]
  [ 5.  0.  0.]]

 [[ 6.  0.  0.]
  [ 7.  0.  0.]]]


In [8]:
print(p)
new(p,17)

print('--------------------------')
print(p)
new(p,1)

[[[ 8.  0.  0.]
  [ 9.  1.  0.]]

 [[10.  2.  0.]
  [ 3.  0.  0.]]

 [[ 4.  0.  0.]
  [ 5.  0.  0.]]

 [[ 6.  0.  0.]
  [ 7.  0.  0.]]]
--------------------------
[[[ 8.  0.  0.]
  [17.  9.  1.]]

 [[10.  2.  0.]
  [ 3.  0.  0.]]

 [[ 4.  0.  0.]
  [ 5.  0.  0.]]

 [[ 6.  0.  0.]
  [ 7.  0.  0.]]]
2구역 다참


array([[[ 8.,  0.,  0.],
        [17.,  9.,  1.]],

       [[10.,  2.,  1.],
        [ 3.,  0.,  0.]],

       [[ 4.,  0.,  0.],
        [ 5.,  0.,  0.]],

       [[ 6.,  0.,  0.],
        [ 7.,  0.,  0.]]])

In [9]:
## 필요하다면 참고 코드 (차원축소)
# a2d=p.reshape(-1,2)# a2d는 차원을 2차원으로 줄인 배열
# print(a2d)
# re=a2d.reshape(4,2,3)#다시 변환해
# print(re)


In [10]:
con_list= p.tolist()
print(con_list)
print(type(con_list))

[[[8.0, 0.0, 0.0], [17.0, 9.0, 1.0]], [[10.0, 2.0, 1.0], [3.0, 0.0, 0.0]], [[4.0, 0.0, 0.0], [5.0, 0.0, 0.0]], [[6.0, 0.0, 0.0], [7.0, 0.0, 0.0]]]
<class 'list'>


In [11]:
mystring=' '.join(map(str,con_list))
print(mystring)
print(type(mystring))
import sys
print(sys.getsizeof(mystring))

[[8.0, 0.0, 0.0], [17.0, 9.0, 1.0]] [[10.0, 2.0, 1.0], [3.0, 0.0, 0.0]] [[4.0, 0.0, 0.0], [5.0, 0.0, 0.0]] [[6.0, 0.0, 0.0], [7.0, 0.0, 0.0]]
<class 'str'>
190


# RDS insert

In [12]:
db=pymysql.connect(host="database-hanium.cijeogglkrqn.ap-northeast-2.rds.amazonaws.com", user="admin",password="gksdldma1234!")


In [13]:
cursor = db.cursor()
cursor

In [14]:
cursor.execute("select version()")


1

In [15]:
data = cursor.fetchone()

In [16]:
data #data version 확인

('10.5.9-MariaDB-log',)

In [21]:
# sql = '''create database sortedcon''' #DB생성
# cursor.execute(sql) #실행

In [23]:
# sql = '''drop database sortedcon'''
# cursor.execute(sql)

In [24]:
cursor.connection.commit()

In [26]:
sql = '''use hanium'''
cursor.execute(sql)

0

In [27]:
sql = '''
CREATE TABLE container(
sort varchar(300)
)
'''
cursor.execute(sql)

0

In [28]:
sql = '''
insert into container(sort) values('%s')''' % (mystring)
cursor.execute(sql)
db.commit()

In [29]:
sql = '''desc container'''
cursor.execute(sql)
cursor.fetchall()
 

(('sort', 'varchar(300)', 'YES', '', None, ''),)

In [30]:
sql = "SELECT * FROM container"
cursor.execute(sql)

result = cursor.fetchall()

print(result)

(('[[8.0, 0.0, 0.0], [17.0, 9.0, 1.0]] [[10.0, 2.0, 1.0], [3.0, 0.0, 0.0]] [[4.0, 0.0, 0.0], [5.0, 0.0, 0.0]] [[6.0, 0.0, 0.0], [7.0, 0.0, 0.0]]',),)
