In [1]:
import random
import numpy as np



In [2]:
import pymysql
pymysql.connect(host="database-hanium.cijeogglkrqn.ap-northeast-2.rds.amazonaws.com", 
                     user="admin", 
                     password="gksdldma1234!")

In [3]:
db=pymysql.connect(host="database-hanium.cijeogglkrqn.ap-northeast-2.rds.amazonaws.com", user="admin",password="gksdldma1234!")


In [4]:
cursor = db.cursor()
cursor

In [5]:
cursor.connection.commit()

In [6]:
sql = '''use hanium'''
cursor.execute(sql)

0

In [7]:
sql = "select sum(a.layer) as 'containerCnt' from (select * from `depth_container` order by `order` desc limit 8) a"
cursor.execute(sql)
result = cursor.fetchall()

print(type(result))
print(result)

<class 'tuple'>
((Decimal('9'),),)


In [8]:
a=result[0][0]
print(a)
print(type(a))


9
<class 'decimal.Decimal'>


In [9]:
len=int(a)
print(len)
print(type(len))

9
<class 'int'>


In [10]:
#a=datetime.today() - timedelta(i)#+사전 컨테이너 레이블링
#b=a.strftime('%d') 
# #dictionary = dict(zip(l,r))
# #print(dictionary)

In [11]:
#!pip install PyMySQL

In [12]:
def rest1(array,date):
    p=array
    if all(p[0,0,0:]==0)==True:
        p[0][0][0]=date
    elif p[0][0][1]==0:
        if p[0][0][0]<=date:
            p[0][0][1]=p[0][0][0]
            p[0][0][0]=date

        elif p[0][0][0]>date:
            p[0][0][1]=date

    elif p[0][0][2]==0:

        if p[0][0][1]>=date:
            p[0][0][2]=date 

        elif p[0][0][1]<date and p[0][0][0]>date:
            p[0][0][2]=p[0][0][1]
            p[0][0][1]=date
        elif p[0][0][0]<=date:
            p[0][0][2]=p[0][0][1]
            p[0][0][1]=p[0][0][0]
            p[0][0][0]=date

    else:
        rest2(p,date)
    return array

def rest2(array,date):
    p=array  
    if all(p[0,1,0:]==0)==True:
        p[0][1][0]=date
    elif p[0][1][1]==0:
        if p[0][1][0]<=date:
            p[0][1][1]=p[0][1][0]
            p[0][1][0]=date

        elif p[0][1][0]>date:
            p[0][1][1]=date

    elif p[0][1][2]==0:

        if p[0][1][1]>=date:
            p[0][1][2]=date 

        elif p[0][1][1]<date and p[0][1][0]>date:
            p[0][1][2]=p[0][1][1]
            p[0][1][1]=date
        elif p[0][1][0]<=date:
            p[0][1][2]=p[0][1][1]
            p[0][1][1]=p[0][1][0]
            p[0][1][0]=date
    else:
        print('2구역 다참')
        rest3(p,date)
    return array

def rest3(array,date):
    p=array
    if all(p[1,0,0:]==0)==True:
        p[1][0][0]=date
    elif p[1][0][1]==0:
        if p[1][0][0]<=date:
            p[1][0][1]=p[1][0][0]
            p[1][0][0]=date

        elif p[1][0][0]>date:
            p[1][0][1]=date

    elif p[1][0][2]==0:

        if p[1][0][1]>=date:
            p[1][0][2]=date 

        elif p[1][0][1]<date and p[1][0][0]>date:
            p[1][0][2]=p[1][0][1]
            p[1][0][1]=date
        elif p[1][0][0]<=date:
            p[1][0][2]=p[1][0][1]
            p[1][0][1]=p[1][0][0]
            p[1][0][0]=date

    else:
        print('3구역 다참')
        rest4(p,date)
    return array

def rest4(array,date):
    p=array
    if all(p[1,1,0:]==0)==True:
        p[1][1][0]=date
    elif p[1][1][1]==0:
        if p[1][1][0]<=date:
            p[1][1][1]=p[1][1][0]
            p[1][1][0]=date

        elif p[1][1][0]>date:
            p[1][1][1]=date

    elif p[1][1][2]==0:

        if p[1][1][1]>=date:
            p[1][1][2]=date 

        elif p[1][1][1]<date and p[1][1][0]>date:
            p[1][1][2]=p[1][1][1]
            p[1][1][1]=date
        elif p[1][1][0]<=date:
            p[1][1][2]=p[1][1][1]
            p[1][1][1]=p[1][1][0]
            p[1][1][0]=date

    else:
        print('4구역 다참')
        rest5(p,date)
            
    return array

def rest5(array,date):
    p=array
    if all(p[2,0,0:]==0)==True:
        p[2][0][0]=date
    elif p[2][0][1]==0:
        if p[2][0][0]<=date:
            p[2][0][1]=p[2][0][0]
            p[2][0][0]=date

        elif p[2][0][0]>date:
            p[2][0][1]=date

    elif p[2][0][2]==0:

        if p[2][0][1]>=date:
            p[2][0][2]=date 

        elif p[2][0][1]<date and p[2][0][0]>date:
            p[2][0][2]=p[2][0][1]
            p[2][0][1]=date
        elif p[2][0][0]<=date:
            p[2][0][2]=p[2][0][1]
            p[2][0][1]=p[2][0][0]
            p[2][0][0]=date

    else:
        print('5구역 다참')
        rest6(p,date)
            
    return array

def rest6(array,date):
    p=array     
    if all(p[2,1,0:]==0)==True:
        p[2][1][0]=date
    elif p[2][1][1]==0:
        if p[2][1][0]<=date:
            p[2][1][1]=p[2][1][0]
            p[2][1][0]=date

        elif p[2][1][0]>date:
            p[2][1][1]=date

    elif p[2][1][2]==0:

        if p[2][1][1]>=date:
            p[2][1][2]=date 

        elif p[2][1][1]<date and p[2][1][0]>date:
            p[2][1][2]=p[2][1][1]
            p[2][1][1]=date
        elif p[2][1][0]<=date:
            p[2][1][2]=p[2][1][1]
            p[2][1][1]=p[2][1][0]
            p[2][1][0]=date

    else:
        print('6구역 다참')
        rest7(array,date)
    return array

def rest7(array,date):
    p=array 
    if all(p[3,0,0:]==0)==True:
        p[3][0][0]=date
    elif p[3][0][1]==0:
        if p[3][0][0]<=date:
            p[3][0][1]=p[3][0][0]
            p[3][0][0]=date

        elif p[3][0][0]>date:
            p[3][0][1]=date

    elif p[3][0][2]==0:

        if p[3][0][1]>=date:
            p[3][0][2]=date 

        elif p[3][0][1]<date and p[3][0][0]>date:
            p[3][0][2]=p[3][0][1]
            p[3][0][1]=date
        elif p[3][0][0]<=date:
            p[3][0][2]=p[3][0][1]
            p[3][0][1]=p[3][0][0]
            p[3][0][0]=date

    else:
        print('7구역 다참')
        rest8(p,date)
    return array

def rest8(array,date):
    p=array 
    if all(p[3,1,0:]==0)==True:
        p[3][1][0]=date
    elif p[3][1][1]==0:
        if p[3][1][0]<=date:
            p[3][1][1]=p[3][1][0]
            p[3][1][0]=date

        elif p[3][1][0]>date:
            p[3][1][1]=date

    elif p[3][1][2]==0:

        if p[3][1][1]>=date:
            p[3][1][2]=date 

        elif p[3][1][1]<date and p[3][1][0]>date:
            p[3][1][2]=p[3][1][1]
            p[3][1][1]=date
        elif p[3][1][0]<=date:
            p[3][1][2]=p[3][1][1]
            p[3][1][1]=p[3][1][0]
            p[3][1][0]=date

    else:
        print('8구역 다참')
        rest1(array,date)
    return array  

In [13]:
def new(array,date):
    p=array
    b=(date%8)+1
    if b==1:
        if all(p[0,0,0:]==0)==True:
            p[0][0][0]=date
        elif p[0][0][1]==0:
            if p[0][0][0]<=date:
                p[0][0][1]=p[0][0][0]
                p[0][0][0]=date
            
            elif p[0][0][0]>date:
                p[0][0][1]=date

        elif p[0][0][2]==0:
           
            if p[0][0][1]>=date:
                p[0][0][2]=date 
            
            elif p[0][0][1]<date and p[0][0][0]>date:
                p[0][0][2]=p[0][0][1]
                p[0][0][1]=date
            elif p[0][0][0]<=date:
                p[0][0][2]=p[0][0][1]
                p[0][0][1]=p[0][0][0]
                p[0][0][0]=date
                
        else:
            print('1구역 다참')
            rest2(p,date)
            

    elif b==2:
        if all(p[0,1,0:]==0)==True:
            p[0][1][0]=date
        elif p[0][1][1]==0:
            if p[0][1][0]<=date:
                p[0][1][1]=p[0][1][0]
                p[0][1][0]=date
            
            elif p[0][1][0]>date:
                p[0][1][1]=date

        elif p[0][1][2]==0:
           
            if p[0][1][1]>=date:
                p[0][1][2]=date 
            
            elif p[0][1][1]<date and p[0][1][0]>date:
                p[0][1][2]=p[0][1][1]
                p[0][1][1]=date
            elif p[0][1][0]<=date:
                p[0][1][2]=p[0][1][1]
                p[0][1][1]=p[0][1][0]
                p[0][1][0]=date
        else:
            print('2구역 다참')
            rest3(p,date)
            
       
        #(1,0-1,y)       
    elif b==3:
        if all(p[1,0,0:]==0)==True:
            p[1][0][0]=date
        elif p[1][0][1]==0:
            if p[1][0][0]<=date:
                p[1][0][1]=p[1][0][0]
                p[1][0][0]=date
            
            elif p[1][0][0]>date:
                p[1][0][1]=date

        elif p[1][0][2]==0:
           
            if p[1][0][1]>=date:
                p[1][0][2]=date 
        
            elif p[1][0][1]<date and p[1][0][0]>date:
                p[1][0][2]=p[1][0][1]
                p[1][0][1]=date
            elif p[1][0][0]<=date:
                p[1][0][2]=p[1][0][1]
                p[1][0][1]=p[1][0][0]
                p[1][0][0]=date
                
        else:
            print('3구역 다참')
            rest4(p,date)
            


    elif b==4:
        if all(p[1,1,0:]==0)==True:
            p[1][1][0]=date
        elif p[1][1][1]==0:
            if p[1][1][0]<=date:
                p[1][1][1]=p[1][1][0]
                p[1][1][0]=date
            
            elif p[1][1][0]>date:
                p[1][1][1]=date

        elif p[1][1][2]==0:
           
            if p[1][1][1]>=date:
                p[1][1][2]=date 
            
            elif p[1][1][1]<date and p[1][1][0]>date:
                p[1][1][2]=p[1][1][1]
                p[1][1][1]=date
            elif p[1][1][0]<=date:
                p[1][1][2]=p[1][1][1]
                p[1][1][1]=p[1][1][0]
                p[1][1][0]=date
                
        else:
            print('4구역 다참')
            rest5(p,date)
            
    #(2,0-1,y) 
    elif b==5:
        if all(p[2,0,0:]==-0)==True:
            p[2][0][0]=date
        elif p[2][0][1]==0:
            if p[2][0][0]<=date:
                p[2][0][1]=p[2][0][0]
                p[2][0][0]=date
            
            elif p[2][0][0]>date:
                p[2][0][1]=date

        elif p[2][0][2]==0:
           
            if p[2][0][1]>=date:
                p[2][0][2]=date 
            
            elif p[2][0][1]<date and p[2][0][0]>date:
                p[2][0][2]=p[2][0][1]
                p[2][0][1]=date
            elif p[2][0][0]<=date:
                p[2][0][2]=p[2][0][1]
                p[2][0][1]=p[2][0][0]
                p[2][0][0]=date
                
        else:
            print('5구역 다참')
            rest6(p,date)
            

        
        
    elif b==6:         
        if all(p[2,1,0:]==0)==True:
            p[2][1][0]=date
        elif p[2][1][1]==0:
            if p[2][1][0]<=date:
                p[2][1][1]=p[2][1][0]
                p[2][1][0]=date
            
            elif p[2][1][0]>date:
                p[2][1][1]=date

        elif p[2][1][2]==0:
           
            if p[2][1][1]>=date:
                p[2][1][2]=date 
            
            elif p[2][1][1]<date and p[2][1][0]>date:
                p[2][1][2]=p[2][1][1]
                p[2][1][1]=date
            elif p[2][1][0]<=date:
                p[2][1][2]=p[2][1][1]
                p[2][1][1]=p[2][1][0]
                p[2][1][0]=date
                
        else:
            print('6구역 다참')
            rest7(p,date)
           
        #(3,0-1,y) 
    elif b==7:
        if all(p[3,0,0:]==0)==True:
            p[3][0][0]=date
        elif p[3][0][1]==0:
            if p[3][0][0]<=date:
                p[3][0][1]=p[3][0][0]
                p[3][0][0]=date
            
            elif p[3][0][0]>date:
                p[3][0][1]=date

        elif p[3][0][2]==0:
           
            if p[3][0][1]>=date:
                p[3][0][2]=date 
            
            elif p[3][0][1]<date and p[3][0][0]>date:
                p[3][0][2]=p[3][0][1]
                p[3][0][1]=date
            elif p[3][0][0]<=date:
                p[3][0][2]=p[3][0][1]
                p[3][0][1]=p[3][0][0]
                p[3][0][0]=date
                
        else:
            print('7구역 다참')
            rest8(p,date)
            

    elif b==8:
        if all(p[3,1,0:]==0)==True:
            p[3][1][0]=date
        elif p[3][1][1]==0:
            if p[3][1][0]<=date:
                p[3][1][1]=p[3][1][0]
                p[3][1][0]=date
            
            elif p[3][1][0]>date:
                p[3][1][1]=date

        elif p[3][1][2]==0:
           
            if p[3][1][1]>=date:
                p[3][1][2]=date 
            
            elif p[3][1][1]<date and p[3][1][0]>date:
                p[3][1][2]=p[3][1][1]
                p[3][1][1]=date
            elif p[3][1][0]<=date:
                p[3][1][2]=p[3][1][1]
                p[3][1][1]=p[3][1][0]
                p[3][1][0]=date
                
        else:
            print('8구역 다참')
            rest1(p,date)
           
            
        
    return array

In [14]:
con=[]#컨테이너 빼는 날짜
for i in range(len):
    a=2021
    b= random.randrange(1,13)
    c= random.randrange(1,31)
    if(b<10 and c<10):
        b="0"+str(b)
        c="0"+str(c)
        d=str(a)+b+c
    elif(b<10 and c>9):
        b="0"+str(b)
        d=str(a)+b+str(c)
    elif(b>9 and c<10):
        c="0"+str(c)
        d=str(a)+str(b)+c
    else:
         d=str(a)+str(b)+str(c)
    date=int(d)
    print(date)
    con.append(date)

20210602
20210521
20210722
20210426
20210128
20210101
20211106
20210308
20211113


In [15]:
l=[] #컨테이너 빼는 날짜+0
for i in range(len):#length(컨테이너개수)
    l.append(con[i])
    
for i in range(24-len):#24-length
    l.append(0)
    
l.sort()
print(l)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 20210101, 20210128, 20210308, 20210426, 20210521, 20210602, 20210722, 20211106, 20211113]


In [16]:
p=np.zeros([4,2,3])

for i in range(24):
    if l[i]==0:
        continue 
    #(0,0-1,y)
    elif (l[i]%8)+1==1:
        if all(p[0,0,0:]==0)==True:
            p[0][0][0]=l[i]
        elif p[0][0][1]==0 and p[0][0][0]<=l[i]:
            p[0][0][1]=p[0][0][0]
            p[0][0][0]=l[i]

        elif p[0][0][2]==0 and p[0][0][1]<=l[i]:
            p[0][0][2]=p[0][0][1]
            p[0][0][1]=p[0][0][0]
            p[0][0][0]=l[i]
        else:
            print('1구역 다참')

    elif (l[i]%8)+1==2:
        if all(p[0,1,0:]==0)==True:
            p[0][1][0]=l[i]
        elif p[0][1][1]==0 and p[0][1][0]<=l[i]:
            p[0][1][1]=p[0][1][0]
            p[0][1][0]=l[i]
        elif p[0][1][2]==0 and p[0][1][1]<=l[i]:
            p[0][1][2]=p[0][1][1]
            p[0][1][1]=p[0][1][0]
            p[0][1][0]=l[i]
        else:
            print('2구역 다참')
    #(1,0-1,y)       
    elif (l[i]%8)+1==3:
        if all(p[1,0,0:]==0)==True:
            p[1][0][0]=l[i]
        elif p[1][0][1]==0 and p[1][0][0]<=l[i]:
            p[1][0][1]=p[1][0][0]
            p[1][0][0]=l[i]
        elif p[1][0][2]==0 and p[1][0][1]<=l[i]:
            p[1][0][2]=p[1][0][1]
            p[1][0][1]=p[1][0][0]
            p[1][0][0]=l[i]
        else:
            print('3구역 다참')

    elif (l[i]%8)+1==4:
        if all(p[1,1,0:]==0)==True:
            p[1][1][0]=l[i]
        elif p[1][1][1]==0 and p[1][1][0]<=l[i]:
            p[1][1][1]=p[1][1][0]
            p[1][1][0]=l[i]
        elif p[1][1][2]==0 and p[1][1][1]<=l[i]:
            p[1][1][2]=p[1][1][1]
            p[1][1][1]=p[1][1][0]
            p[1][1][0]=l[i]
        else:
            print('4구역 다참')
    #(2,0-1,y) 
    elif (l[i]%8)+1==5:
        if all(p[2,0,0:]==0)==True:
            p[2][0][0]=l[i]
        elif p[2][0][1]==0 and p[2][0][0]<=l[i]:
            p[2][0][1]=p[2][0][0]
            p[2][0][0]=l[i]
        elif p[2][0][2]==0 and p[2][0][1]<=l[i]:
            p[2][0][2]=p[2][0][1]
            p[2][0][1]=p[2][0][0]
            p[2][0][0]=l[i]
        else:
            print('5구역 다참')
    elif (l[i]%8)+1==6:         
        if all(p[2,1,0:]==0)==True:
            p[2][1][0]=l[i]
        elif p[2][1][1]==0 and p[2][1][0]<=l[i]:
            p[2][1][1]=p[2][1][0]
            p[2][1][0]=l[i]
        elif p[2][1][2]==0 and p[2][1][1]<=l[i]:
            p[2][1][2]=p[2][1][1]
            p[2][1][1]=p[2][1][0]
            p[2][1][0]=l[i]
        else:
            print('6구역 다참')
    #(3,0-1,y) 
    elif (l[i]%8)+1==7: 
        if all(p[3,0,0:]==0)==True:
            p[3][0][0]=l[i]
        elif p[3][0][1]==0 and p[3][0][0]<=l[i]:
            p[3][0][1]=p[3][0][0]
            p[3][0][0]=l[i]
        elif p[3][0][2]==0 and p[2][0][1]<=l[i]:
            p[3][0][2]=p[3][0][1]
            p[3][0][1]=p[3][0][0]
            p[3][0][0]=l[i]
        else:
            print('7구역 다참')

    elif (l[i]%8)+1==8:   
        if all(p[3,1,0:]==0)==True:
            p[3][1][0]=l[i]
        elif p[3][1][1]==0 and p[3][1][0]<=l[i]:
            p[3][1][1]=p[3][1][0]
            p[3][1][0]=l[i]
        elif p[3][1][2]==0 and p[3][1][1]<=l[i]:
            p[3][1][2]=p[3][1][1]
            p[3][1][1]=p[3][1][0]
            p[3][1][0]=l[i]
        else:
            print('8구역 다참')

print(p)

3구역 다참
[[[20210128.        0.        0.]
  [20211113. 20210521.        0.]]

 [[20210722. 20210602. 20210426.]
  [       0.        0.        0.]]

 [[20210308.        0.        0.]
  [20210101.        0.        0.]]

 [[       0.        0.        0.]
  [       0.        0.        0.]]]


In [17]:
print(p)
new(p,17)

print('--------------------------')
print(p)
new(p,1)
# b = np.where(a=8, ' arrt', a)

[[[20210128.        0.        0.]
  [20211113. 20210521.        0.]]

 [[20210722. 20210602. 20210426.]
  [       0.        0.        0.]]

 [[20210308.        0.        0.]
  [20210101.        0.        0.]]

 [[       0.        0.        0.]
  [       0.        0.        0.]]]
--------------------------
[[[2.0210128e+07 0.0000000e+00 0.0000000e+00]
  [2.0211113e+07 2.0210521e+07 1.7000000e+01]]

 [[2.0210722e+07 2.0210602e+07 2.0210426e+07]
  [0.0000000e+00 0.0000000e+00 0.0000000e+00]]

 [[2.0210308e+07 0.0000000e+00 0.0000000e+00]
  [2.0210101e+07 0.0000000e+00 0.0000000e+00]]

 [[0.0000000e+00 0.0000000e+00 0.0000000e+00]
  [0.0000000e+00 0.0000000e+00 0.0000000e+00]]]
2구역 다참
3구역 다참


array([[[2.0210128e+07, 0.0000000e+00, 0.0000000e+00],
        [2.0211113e+07, 2.0210521e+07, 1.7000000e+01]],

       [[2.0210722e+07, 2.0210602e+07, 2.0210426e+07],
        [1.0000000e+00, 0.0000000e+00, 0.0000000e+00]],

       [[2.0210308e+07, 0.0000000e+00, 0.0000000e+00],
        [2.0210101e+07, 0.0000000e+00, 0.0000000e+00]],

       [[0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00]]])

In [ ]:
## 필요하다면 참고 코드 (차원축소)
# a2d=p.reshape(-1,2)# a2d는 차원을 2차원으로 줄인 배열
# print(a2d)
# re=a2d.reshape(4,2,3)#다시 변환해
# print(re)


In [18]:
con_list= p.tolist()
print(con_list)
print(type(con_list))

[[[20210128.0, 0.0, 0.0], [20211113.0, 20210521.0, 17.0]], [[20210722.0, 20210602.0, 20210426.0], [1.0, 0.0, 0.0]], [[20210308.0, 0.0, 0.0], [20210101.0, 0.0, 0.0]], [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0]]]
<class 'list'>


In [19]:
mystring=' '.join(map(str,con_list))
print(mystring)
print(type(mystring))
import sys
print(sys.getsizeof(mystring))

[[20210128.0, 0.0, 0.0], [20211113.0, 20210521.0, 17.0]] [[20210722.0, 20210602.0, 20210426.0], [1.0, 0.0, 0.0]] [[20210308.0, 0.0, 0.0], [20210101.0, 0.0, 0.0]] [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0]]
<class 'str'>
245


# RDS insert

In [ ]:
import pymysql
pymysql.connect(host="database-hanium.cijeogglkrqn.ap-northeast-2.rds.amazonaws.com", 
                     user="admin", 
                     password="gksdldma1234!")

In [ ]:
db=pymysql.connect(host="database-hanium.cijeogglkrqn.ap-northeast-2.rds.amazonaws.com", user="admin",password="gksdldma1234!")


In [ ]:
cursor = db.cursor()
cursor

In [ ]:
cursor.execute("select version()")


In [ ]:
data = cursor.fetchone()

In [ ]:
data #data version 확인

In [ ]:
# sql = '''create database sortedcon''' #DB생성
# cursor.execute(sql) #실행

In [ ]:
# sql = '''drop database sortedcon'''
# cursor.execute(sql)

In [ ]:
cursor.connection.commit()

In [ ]:
sql = '''use hanium'''
cursor.execute(sql)

In [ ]:
sql = '''
CREATE TABLE container(
sort varchar(300)
)
'''
cursor.execute(sql)

In [ ]:
sql = '''
insert into container(sort) values('%s')''' % (mystring)
cursor.execute(sql)
db.commit()

In [ ]:
sql = '''desc container'''
cursor.execute(sql)
cursor.fetchall()
 

In [ ]:
sql = "SELECT * FROM container"
cursor.execute(sql)

result = cursor.fetchall()

print(result)